# Generated by Django 5.0.1 on 2024-01-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislike',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
