# Generated by Django 5.0.1 on 2024-01-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_dislikes_post_likes_alter_dislike_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='count',
        ),
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
