# Generated by Django 5.0.1 on 2024-01-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('release_year', models.CharField(max_length=32)),
                ('genre', models.CharField(choices=[('action', 'action'), ('comedy', 'comedy'), ('drama', 'drama'), ('romance', 'romance'), ('SF', 'SF')], max_length=20)),
                ('star_score', models.FloatField()),
                ('running_time', models.IntegerField()),
                ('content', models.TextField()),
                ('director', models.CharField(max_length=32)),
                ('actor', models.CharField(max_length=32)),
            ],
        ),
    ]
